# Name: Josh Archer
# Date: 6/23/2019
# Filename: pixels.py
# Description: This file has a few functions to help draw
# pixels in a 4_introduction_to_turtle program. DO NOT EDIT THIS FILE!

# store the size of the pen
size = 10

def setPixelSize(newSize) :
    global size
    size = newSize

def drawSquare(pen, x, y, color) :
    # move to the position
    pen.up()
    pen.goto(x * size, y * size)
    pen.down()

    #set the color
    pen.color("black", color)

    pen.begin_fill()
    pen.setheading(0) # east
    pen.forward(size)
    pen.right(90)
    pen.forward(size)
    pen.right(90)
    pen.forward(size)
    pen.right(90)
    pen.forward(size)
    pen.end_fill()